### PR TITLE
📚 Fix step reference in installation steps

### PR DESCRIPTION
**Pull request by mchangsp**
# Proposed Changes
Changed the step where a referral is made to the step where the token is obtained

> (Describe the changes and rationale behind them)

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by frenck** [comment]
Looks ok, any reason you kept the PR marked as draft @mchangsp?

../Frenck

**Comment by mchangsp** [comment]
I got an error in the github actions. Tried to edit the pull request to add a label. I guess I cannot add a label

**Comment by frenck** [comment]
I did that just now? Adding labels is something maintainers do...

**Comment by mchangsp** [comment]
I just closed the PR. is that okay?

**Review by frenck — APPROVED** [review]
Thanks, @mchangsp 👍 

Happy New Year 🥂 

../Frenck

**Comment by mchangsp** [comment]
Thanks! Happy new year to you too!

**Pull request merged**
