### PR TITLE
Multiarch

### PR DESCRIPTION
**Pull request by colinfrei**
# Proposed Changes

With the [1.1.6.0 release](https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.16.0), bitwardenrs changed their docker images to make use of multiarch support. Docker images with architecture tags won't be updated in the future.

### CODE REVIEW

**Comment by frenck** [comment]
Which they have partly reverted already, as they discovered it doesn't always work as expected.

Could you elaborate on how this PR solves that issue? As I only see the removal of stuff, but not the addition of a replacement?

**Comment by colinfrei** [comment]
My understanding is that the multiarch doesn't work for arm32v6:
https://github.com/dani-garcia/bitwarden_rs/wiki/Which-container-image-to-use#images
> [...] with the exception of Armv6 boards, such as Raspberry Pi 1 and Zero (see moby/moby#41017). Armv6 users must specify arm32v6 in the image tag, e.g. latest-arm32v6.


As far as I can tell that architecture isn't supported by home assistant anyway (looking at [ADR 0013](https://github.com/home-assistant/architecture/blob/master/adr/0013-home-assistant-container.md#supported-boardshardwaremachines) and [ADR 0015](https://github.com/home-assistant/architecture/blob/master/adr/0015-home-assistant-os.md#supported-boardshardwaremachines))

I'm happy to add a build step for arm32v6 if you think that'd be helpful.

**Comment by frenck** [comment]
Sure, but that doesn't answer my last question:

> Could you elaborate on how this PR solves that issue? As I only see the removal of stuff, but not the addition of a replacement?

**Comment by colinfrei** [comment]
ah sure, sorry, I misread that.

My thinking is that by removing the build steps it'll fall back to the [default build step](https://github.com/hassio-addons/organization/blob/master/gitlabci/addon.yml#L101) for all three architectures, and build images for all three using the multiarch bitwardenrs image.

Unfortunately it's untested as I don't have gitlab set up to actually run the build jobs. If you have any input on what's necessary additionally or how I could test this myself that's very welcome :)

**Comment by colinfrei** [comment]
do you have any further input/questions on this?

**Comment by frenck** [comment]
yes, your suggestions won't work.

**Comment by colinfrei** [comment]
If you can give me any pointers on where to look or how to test this I'd be happy to find a working solution.
If it's easier for you to look into this yourself that's fine with me as well.

My motivation is mostly to get the latest version of bitwarden_rs available, to solve issues like #31

**Comment by frenck** [comment]
We have to make sure the right architecture is picked for each BUILD_ARCH passed in as a build argument. We cannot rely on Docker to handle this (as for cross-build, a 64 bits ARM CPU could be used to build the 32 bits ARM version; if the build server supports the 32 bits instructions).

**Comment by colinfrei** [comment]
I've tried something using the --platform argument for FROM: https://docs.docker.com/engine/reference/builder/#from

That said, I'm in a bit over my head. I tried setting up the gitlab ci pipeline, but didn't get that to work without having the runners set up, so I unfortunately have no way to test/experiment :)

**Comment by sinclairpaul** [comment]
I did some testing on the changes, a couple of comments:

How will amd64 build if BITWARDEN_PLATFORM is null?

Is it worth defaulting it for local building?

From what I can see it appears to pull the correct images, tested with 32 and 64 bit arm.

I wouldn't recommend bumping the version in the same PR.

I don't know if this is the best approach (although I am not sure of any other), but in theory it appears to work ok.

**Comment by Keltere** [comment]
> I did some testing on the changes, a couple of comments:
> 
> How will amd64 build if BITWARDEN_PLATFORM is null?
> 
> Is it worth defaulting it for local building?
> 
> From what I can see it appears to pull the correct images, tested with 32 and 64 bit arm.
> 
> I wouldn't recommend bumping the version in the same PR.
> 
> I don't know if this is the best approach (although I am not sure of any other), but in theory it appears to work ok.

Sorry but how did you tested it?

**Comment by colinfrei** [comment]
> How will amd64 build if BITWARDEN_PLATFORM is null?

That's a good point - I'm not sure how docker behaves if --platform is passed in without an argument. I'm not sure setting the default to linux/amd64 makes sense, maybe just to _linux_ - wdyt?

>I wouldn't recommend bumping the version in the same PR.

My thought was since the last few versions of bitwardenrs had changes to multiarch, it'd be best to use the latest multiarch setup.

**Comment by frenck** [comment]
I'm closing this PR.

All I see here is guessing to get things to work and no actual progress besides a PR that will not work at all. We are not using Docker's experimental buildx feature either, so this will not work.

Thanks for contributing.

**Pull request closed without merging**
